void choose(char menu_board[20][41]);
void my_words();
void INSTRUCTIONS();
void menu();
void game_play();
void put_score(int n,int speed); 
void delete_it(int i);
void game_board_new();
void history();
void music_menu();
void music_menu_colse();
void music_play();
void music_play_close();
void set_up();
int is_change(int* n2);
void printf_board();
void load(int score,int ti);
void printf_history(int y,int x);
int  auto_move(int n);
int  is_rl(int nm, int n2);
int  wfigure_1(int n);
int  wfigure_2(int n);
int  wfigure_3(int n);
int  wfigure_4(int n);
int  wfigure_5(int n);
int  wfigure_6(int n);
int  wfigure_7(int n);
int  wfigure_8(int n);
int  wfigure_9(int n);
int  wfigure_10(int n);
int  wfigure_11(int n);
int  wfigure_12(int n);
int  wfigure_13(int n);
int  wfigure_14(int n);
int  wfigure_15(int n);
int  wfigure_16(int n);
int  wfigure_17(int n);
int  wfigure_18(int n);
int  wfigure_19(int n);
int  wfigure_20(int n);
int  hfigure_1();
int  hfigure_2();
int  hfigure_3();
int  hfigure_4();
int  hfigure_5();
int  hfigure_6();
int  hfigure_7();
int  hfigure_8();
int  hfigure_9();
int  hfigure_10();
int  hfigure_11();
int  hfigure_12();
int  hfigure_13();
int  hfigure_14();
int  hfigure_15();
int  hfigure_16();
int  hfigure_17();
int  hfigure_18();
int  hfigure_19();
int  hfigure_20();
int  is_delete();
struct player_date
{
	int year;
	int month;
	int day;
	int hour;
	int minute;
	int second;
};
struct player
{
	char name[20];
	int large;
	int speed_ini;
	int h;
	char phone[15];
	int score;
	char time[20];
	int min;
	int se;
	struct player_date _date;
	struct player* next;
	struct player* last;
};
